MERGE TTarget AS TARGET
USING TSource AS SOURCE
ON (TARGET.Id = SOURCE.Id)


WHEN MATCHED AND TARGET.FruitName <> SOURCE.FruitName
OR TARGET.Cost <> SOURCE.Cost THEN
UPDATE SET TARGET.FruitName = SOURCE.FruitName,
TARGET.Cost = SOURCE.Cost

WHEN NOT MATCHED BY TARGET THEN
INSERT(Id, FruitName, Cost)
VALUES (SOURCE.Id, SOURCE.FruitName, SOURCE.Cost)

WHEN NOT MATCHED BY SOURCE THEN
DELETE

OUTPUT $action,
DELETED.Id AS TargetedId,
DELETED.FruitName AS TargetedName,
DELETED.Cost AS TargetedCost,
INSERTED.Id AS SourceId,
INSERTED.FruitName AS SourceName,
INSERTED.Cost AS SourceCost;

SELECT @@ROWCOUNT
GO